"""
PharmaPulse CI — Professional Multi-Tab Excel Exporter
======================================================
Generates an executive-ready, 6-sheet styled .xlsx workbook
including Clinical Pipeline, Forecasting Milestones, Efficacy Benchmarks,
Patent & Exclusivity, and FDA Regulatory Dossier.
"""

import io
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from typing import Dict, Any


HEADER_FILL = PatternFill(start_color="1A2133", end_color="1A2133", fill_type="solid")
HEADER_FONT = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
PIVOTAL_FILL = PatternFill(start_color="FFF1F2", end_color="FFF1F2", fill_type="solid")
BORDER_THIN = Side(border_style="thin", color="D1D5DB")
CELL_BORDER = Border(left=BORDER_THIN, right=BORDER_THIN, top=BORDER_THIN, bottom=BORDER_THIN)


def autofit_columns(ws, max_len_cap=65):
    """Adjusts column widths based on cell content length."""
    for col in ws.columns:
        max_len = 0
        col_letter = get_column_letter(col[0].column)
        for cell in col:
            val_str = str(cell.value or "")
            if len(val_str) > max_len:
                max_len = len(val_str)
        ws.column_dimensions[col_letter].width = min(max(max_len + 3, 12), max_len_cap)


def generate_excel_dossier(dossier: Dict[str, Any]) -> io.BytesIO:
    """Creates a 6-sheet formatted Excel workbook in memory."""
    wb = openpyxl.Workbook()
    wb.remove(wb.active)

    drug_name = dossier.get("drug_name", "Drug Intelligence")
    trials = dossier.get("trials", [])
    stats = dossier.get("stats", {})
    fda = dossier.get("fda", {})
    forecasting = dossier.get("forecasting", {})
    pubmed = dossier.get("pubmed", {})
    patent = dossier.get("patent", {})
    efficacy = dossier.get("efficacy", [])

    # =========================================================================
    # SHEET 1: Executive Summary
    # =========================================================================
    ws1 = wb.create_sheet(title="Executive Summary")
    ws1.views.sheetView[0].showGridLines = True

    ws1.append(["PharmaPulse CI — Executive Intelligence Summary"])
    ws1.merge_cells("A1:D1")
    ws1["A1"].font = Font(name="Calibri", size=14, bold=True, color="1A2133")

    ws1.append(["Drug / Target Analyzed:", drug_name.title()])
    ws1.append(["Report Generated By:", "PharmaPulse CI Intelligence Engine"])
    ws1.append([])

    ws1.append(["Key Commercial & Clinical Metrics", "Value"])
    ws1["A5"].font = Font(bold=True)
    ws1["B5"].font = Font(bold=True)

    metrics = [
        ("Total Registered Trials", stats.get("total_trials", 0)),
        ("Pivotal / Registrational Trials", stats.get("pivotal_trials", 0)),
        ("Pivotal Trials Percentage", f"{stats.get('pivotal_percentage', 0)}%"),
        ("Total Clinical Patients Enrolled", f"{stats.get('total_enrolled', 0):,}"),
        ("Currently Recruiting Studies", stats.get("recruiting_trials", 0)),
        ("FDA Approved Status", "Approved (Label Found)" if fda.get("label", {}).get("found") else "Investigational / Not Approved"),
        ("FDA Brand / Generic Name", f"{fda.get('label',{}).get('brand_name','')} / {fda.get('label',{}).get('generic_name','')}"),
        ("Earliest Commercial Launch / Readout", forecasting.get("earliest_projected_launch", "N/A")),
        ("Primary Patent Expiration (LOE)", f"{patent.get('patent_expiry_formatted','N/A')} ({patent.get('primary_patent','')})"),
        ("Commercial Monopoly Runway", f"{patent.get('runway_years', 0.0)} Years Remaining"),
        ("Regulatory Exclusivity Status", patent.get("status_label", "N/A")),
        ("Total Published Papers (PubMed)", pubmed.get("total_papers", 0)),
        ("Clinical Trial Papers (PubMed)", pubmed.get("clinical_trial_papers", 0)),
        ("Reported Adverse Event Cases", f"{fda.get('safety',{}).get('total',0):,} (Serious: {fda.get('safety',{}).get('serious',0):,})")
    ]

    for label, val in metrics:
        ws1.append([label, val])

    autofit_columns(ws1)

    # =========================================================================
    # SHEET 2: Clinical Pipeline & Pivotal Trials
    # =========================================================================
    ws2 = wb.create_sheet(title="Clinical Pipeline")
    ws2.views.sheetView[0].showGridLines = True
    ws2.freeze_panes = "A2"

    headers_trials = [
        "NCT ID", "Pivotal Trial?", "Pivotal Score", "Phase", "Study Status",
        "Enrollment", "Lead Sponsor", "Primary Completion Date",
        "Brief Title", "Primary Endpoint / Measure", "Conditions", "Registry Link"
    ]
    ws2.append(headers_trials)
    for col_num in range(1, len(headers_trials) + 1):
        cell = ws2.cell(row=1, column=col_num)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal="center", vertical="center")

    for t in trials:
        is_piv = "YES" if t.get("is_pivotal") else "No"
        row_vals = [
            t.get("nct_id", ""),
            is_piv,
            t.get("pivotal_score", 0),
            t.get("phase", ""),
            t.get("status", ""),
            t.get("enrollment", 0),
            t.get("sponsor", ""),
            t.get("primary_completion_date", ""),
            t.get("title", ""),
            "; ".join(t.get("primary_outcomes", [])),
            "; ".join(t.get("conditions", [])),
            t.get("url", "")
        ]
        ws2.append(row_vals)
        current_row = ws2.max_row
        if is_piv == "YES":
            for c in range(1, len(row_vals) + 1):
                ws2.cell(row=current_row, column=c).fill = PIVOTAL_FILL

    autofit_columns(ws2)

    # =========================================================================
    # SHEET 3: Forecasting Milestones
    # =========================================================================
    ws3 = wb.create_sheet(title="Forecasting Milestones")
    ws3.views.sheetView[0].showGridLines = True
    ws3.freeze_panes = "A2"

    headers_fc = [
        "NCT ID", "Phase", "Status", "Pivotal?", "Sample Size",
        "Primary Completion (PCD)", "Topline Readout Window",
        "Regulatory Filing Window", "PDUFA (Priority - 6mo)",
        "PDUFA (Standard - 10mo)", "Est. Commercial Launch", "Launch Year"
    ]
    ws3.append(headers_fc)
    for col_num in range(1, len(headers_fc) + 1):
        cell = ws3.cell(row=1, column=col_num)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal="center", vertical="center")

    for m in forecasting.get("milestones", []):
        row_vals = [
            m.get("nct_id", ""),
            m.get("phase", ""),
            m.get("status", ""),
            "YES" if m.get("is_pivotal") else "No",
            m.get("enrollment", 0),
            m.get("pcd_formatted", "N/A"),
            m.get("topline_readout", "N/A"),
            m.get("regulatory_filing", "N/A"),
            m.get("pdufa_priority", "N/A"),
            m.get("pdufa_standard", "N/A"),
            m.get("commercial_launch", "N/A"),
            m.get("calendar_year_launch", "N/A")
        ]
        ws3.append(row_vals)

    autofit_columns(ws3)

    # =========================================================================
    # SHEET 4: Clinical Efficacy Benchmarks
    # =========================================================================
    ws4 = wb.create_sheet(title="Efficacy Benchmarks")
    ws4.views.sheetView[0].showGridLines = True
    ws4.freeze_panes = "A2"

    headers_eff = ["Clinical Endpoint", "Treatment Result", "Comparator / Placebo Delta", "Statistical Significance", "Source Trial / Publication"]
    ws4.append(headers_eff)
    for col_num in range(1, len(headers_eff) + 1):
        cell = ws4.cell(row=1, column=col_num)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal="center", vertical="center")

    for eff in efficacy:
        ws4.append([
            eff.get("endpoint", ""),
            eff.get("treatment_value", ""),
            eff.get("delta", ""),
            eff.get("stat_sig", ""),
            eff.get("flagship_trial", "")
        ])

    autofit_columns(ws4)

    # =========================================================================
    # SHEET 5: FDA Regulatory Dossier
    # =========================================================================
    ws5 = wb.create_sheet(title="FDA Regulatory Dossier")
    ws5.views.sheetView[0].showGridLines = True

    lbl = fda.get("label", {})
    ws5.append(["FDA Regulatory & Prescribing Label Information", ""])
    ws5["A1"].font = Font(size=13, bold=True)
    ws5.append(["Brand Name:", lbl.get("brand_name", "N/A")])
    ws5.append(["Generic Name:", lbl.get("generic_name", "N/A")])
    ws5.append(["NDA / BLA Numbers:", ", ".join(lbl.get("application_numbers", []))])
    ws5.append(["Manufacturer:", lbl.get("manufacturer", "N/A")])
    ws5.append(["Primary Patent Expiry:", patent.get("patent_expiry_formatted", "N/A")])
    ws5.append(["Commercial Monopoly Runway:", f"{patent.get('runway_years', 0.0)} Years Remaining"])
    ws5.append(["Has Boxed Warning:", "YES (Black Box Warning)" if lbl.get("has_boxed_warning") else "None"])
    ws5.append([])
    ws5.append(["Indications & Usage (Approved):"])
    ws5["A10"].font = Font(bold=True)
    ws5.append([lbl.get("indications_and_usage", "No indication text found.")])
    ws5.append([])
    ws5.append(["Boxed Warnings (Safety):"])
    ws5["A13"].font = Font(bold=True)
    ws5.append([lbl.get("boxed_warning", "No boxed warning reported.")])

    autofit_columns(ws5, max_len_cap=90)

    # =========================================================================
    # SHEET 6: PubMed Key Publications
    # =========================================================================
    ws6 = wb.create_sheet(title="PubMed Publications")
    ws6.views.sheetView[0].showGridLines = True
    ws6.freeze_panes = "A2"

    headers_pm = ["PMID", "High Impact?", "Title", "Lead Authors", "Journal", "Publication Date", "PubMed URL"]
    ws6.append(headers_pm)
    for col_num in range(1, len(headers_pm) + 1):
        cell = ws6.cell(row=1, column=col_num)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal="center", vertical="center")

    for p in pubmed.get("papers", []):
        row_vals = [
            p.get("pmid", ""),
            "★ High Impact" if p.get("is_high_impact") else "Standard",
            p.get("title", ""),
            p.get("authors", ""),
            p.get("journal", ""),
            p.get("pub_date", ""),
            p.get("url", "")
        ]
        ws6.append(row_vals)

    autofit_columns(ws6)

    stream = io.BytesIO()
    wb.save(stream)
    stream.seek(0)
    return stream
